apiVersion: batch/v1
kind: Job
metadata:
  name: minio-fulladmin-setup
  namespace: minio
spec:
  backoffLimit: 3
  template:
    spec:
      restartPolicy: Never
      containers:
      - name: mc
        image: minio/mc
        command: ["/bin/sh", "-c"]
        args:
          - |
            echo "⏳ Waiting for MinIO...";
            until mc alias set minio http://minio-service.minio.svc.cluster.local:9000 minioadmin minioadmin; do sleep 3; done

            echo " Creating full-access policy...";
            echo '{
              "Version": "2012-10-17",
              "Statement": [
                {
                  "Effect": "Allow",
                  "Action": ["admin:*", "s3:*"],
                  "Resource": ["*"]
                }
              ]
            }' > /tmp/fullaccess-policy.json

            mc admin policy create minio fullaccess-policy /tmp/fullaccess-policy.json

            echo "✅ Creating user fulladmin...";
            mc admin user add minio fulladmin fulladmin123

            echo "✅ Attaching policy to user...";
            mc admin policy attach minio fullaccess-policy --user fulladmin

            echo " Full IAM access setup complete!"
        env:
          - name: MC_HOST_minio
            value: http://minioadmin:minioadmin@minio-service.minio.svc.cluster.local:9000
